#!/usr/bin/env python

import sys,os,cgi,json,cgitb,socket
import boto.sqs
cgitb.enable()

print "Content-Type: text/plain;charset=utf-8"
print

form = cgi.FieldStorage()
x = form.getvalue('x',None)
y = form.getvalue('y',None)
op = form.getvalue('op',None)

if    x  is None: resp=['err', 'x is required']
elif  y  is None: resp=['err', 'y is required']
elif op  is None: resp=['err','op is required']
elif op == 'add': resp=['ok', int(x)+int(y)]
elif op == 'mul': resp=['ok', int(x)*int(y)]
elif op == 'sub': resp=['ok', int(x)-int(y)]
elif op == 'div' and int(y) == 0: resp=['err', 'division by zero']
elif op == 'div': resp=['ok', int(x)/int(y)]
else: resp=['err', 'op must be: add/mul/sub/div']

remote_addr=os.environ.get('REMOTE_ADDR','not-set')
server_name=os.environ.get('SERVER_NAME','not-set')
hostname=socket.gethostname()

sqsconn=boto.sqs.connect_to_region('us-west-2')
mathq=sqsconn.get_queue('mathq')
m=boto.sqs.message.Message()
resp.append({'server':server_name,'remote':remote_addr,'host':hostname})
s=json.dumps(resp,separators=(',',':'))
m.set_body(s)
mathq.write(m)

print json.dumps(resp)
