#!/bin/sh
IP=$1
rm -f test2.out
(curl -s 'http://$IP/cgi-bin/mathserver?op=add&x=4&y=5'
curl -s 'http://$IP/cgi-bin/mathserver?op=sub&x=4&y=5'
curl -s 'http://$IP/cgi-bin/mathserver?op=mul&x=4&y=5'
curl -s 'http://$IP/cgi-bin/mathserver?op=div&x=4&y=5') >test2.out
diff test2.out test2.expected
if test $? -eq 0; then
    echo good
    rm test2.out
fi
