#!/usr/local/sqlminus/bin/python
"""
awsh -- aws shell

    https://github.com/awsh             :  share and enjoy!
    Mark Harrison, marhar@gmail.com     :
"""

import os,sys,readline,cmd,atexit,ConfigParser,traceback,subprocess
import fnmatch,pprint,urllib2
import boto.ec2
import awshelpers
from awshelpers import P,P0,D,D0

class AwshCmd(cmd.Cmd):
    """--------------------------------------------------\n"""\
    """| Welcome to awsh, the AWS shell                 |\n"""\
    """| docs: https://github.com/marhar/aws            |\n"""\
    """| type "help" for help                  build<3> |\n"""\
    """--------------------------------------------------\n"""

    #===================================================================
    # Cmd-related things
    #===================================================================

    #-------------------------------------------------------------------
    def __init__(self):
        """AwshCmd init"""
        cmd.Cmd.__init__(self)

        config=awshelpers.readconfig('config')
        self.region = config['default']['region']
        self.output = config['default']['output']

        ebconfig=awshelpers.readconfig('ebconfig')
        try:
            self.name = ebconfig['default']['name']
        except KeyError:
            self.name = 'setNameInEBCONFIG'
        try:
            self.pemfile = ebconfig['default']['pemfile']
        except KeyError:
            self.pemfile = 'setPemFileInEBCONFIG'

        self.conn = boto.ec2.connect_to_region(self.region)
        self.prompt='%s@%s> '%(self.name,self.region)

    #-------------------------------------------------------------------
    def emptyline(self):
        """ignore empty lines"""
        pass

    #-------------------------------------------------------------------
    def do_EOF(self,s):
        """quit"""
        P('')
        sys.exit(0);

    #===================================================================
    # shell commands
    #===================================================================

    #-----------------------------------------------------------------------
    def do_config(self,s):
        """print information about this account"""
        P('   region: %s'%(self.region))
        P('   output: %s'%(self.output))
        P('     name: %s'%(self.name))
        P('  pemfile: %s'%(self.pemfile))

    #-----------------------------------------------------------------------
    def do_reservations(self,s):
        """display reservations"""
        # TODO: figure out any more useful info to display?
        # BUG: nuke i0, should be for instance in instances???
        reservations=self.conn.get_all_reservations()
        for r in reservations:
            P('  '+str(r))
            instances=r.instances
            i0=instances[0]
            P('    '+i0.id)
            P('      '+i0.instance_type)
            P('      '+i0.placement)

    #-----------------------------------------------------------------------
    def do_myip(self,s):
        """what's my ip address according to amazon?"""
        fd=urllib2.urlopen("http://checkip.amazonaws.com")
        ip=fd.read()
        print(ip.strip())

    #-----------------------------------------------------------------------
    def _attrlist(self,obj, attrs):
        """get a list of named attributes from an object"""
        vlist = [obj.__getattribute__(attr) for attr in attrs]
        return vlist
        
    #-----------------------------------------------------------------------
    def do_instances(self,s):
        """print information about instances"""

        dat=[]
        headers='id ip_address instance_type placement state'.split()
        for r in self.conn.get_all_reservations():
            for inst in r.instances:
                if inst.state != 'terminated':
                    dat.append(self._attrlist(inst,headers))
        awshelpers.tprintx(headers,dat)

    #-----------------------------------------------------------------------
    def do_volumes(self,s):
        """print information about volumes"""
        # TODO: what else is useful? tags? snapshots? dir(v)

        dat=[]
        headers='id type zone iops size status'.split()
        for v in self.conn.get_all_volumes():
            row=[v.id,v.type,v.zone,v.iops, v.size, v.status]
            dat.append(row)
        awshelpers.tprintx(headers,dat)

    #-----------------------------------------------------------------------
    def do_ssh(self,s):
        """show ssh commands for running nodes"""
        for r in self.conn.get_all_reservations():
            for i0 in r.instances:
                if i0.state in ['running','pending']:
                    addr=str(i0.ip_address)
                    P('ssh -i %s/.aws/%s ec2-user@%s'% \
                      (os.environ['HOME'],self.pemfile,addr))

    #-----------------------------------------------------------------------
    def do_curltest(self,s):
        """show curl commands for running nodes"""
        for r in self.conn.get_all_reservations():
            for inst in r.instances:
                if inst.state in ['running']:
                    P('curl http://%s'%(inst.ip_address))
                    P('curl http://%s/cgi-bin/working'%(inst.ip_address))

    #-----------------------------------------------------------------------
    def do_div0(self,s):
        """devel: test case for runtime error reporting"""
        x=1/0
        #TODO: add build number, auto report bug

    #-----------------------------------------------------------------------
    def _instancelist(self):
        """return a list of instances and statuses"""

        rv=[]
        for resv in self.conn.get_all_reservations():
            for inst in resv.instances:
                rv.append([inst.id,inst.state])
        return rv

    #-----------------------------------------------------------------------
    def complete_start(self, text, line, begidx, endidx):
        """start completions: instances which are not running"""
        #TODO: need to handle multiple completions per line
        #BUG: needs some fiddling

        #print 'text<%s,%s,%s,%s>'%(text,line,begidx,endidx)
        x=self._instancelist()

        hlen=len('start ')  # TODO: should be able to skip using begidx?
        partial=line[hlen:].strip()

        if len(partial) == 0:
            rv=[i[0] for i in x if i[1] not in 'running']
        else:
            plen=len(partial)
            rv=[i[0][plen-1:] for i in x if i[0].startswith(partial)
                                    and i[1] not in 'running']
        return rv

    #-----------------------------------------------------------------------
    def do_start(self,s):
        """start one or more instances"""

        a=s.split()
        if len(a) == 0:
            P('    usage: start instancelist...')
            return

        started_states=['pending','running','terminated']
        # b is list of instances match that match wc
        b=[]
        for wc in a:
            if wc.find('*')==-1 and wc.find('?')==-1:
                b.append(wc)
            else:
                for c in [i[0] for i in self._instancelist() \
                                 if i[1] not in started_states]:
                    if fnmatch.fnmatch(c,wc):
                        b.append(c)

        if len(b) == 0:
            P('    error: no unstarted instance matches: %s'%s)
            return

        try:
            rv=self.conn.start_instances(instance_ids=b)
            for i in rv:
                P('    starting: %s'%(i))
        except boto.exception.EC2ResponseError,e:
            P('    error: %s'%(e.message))


    #-----------------------------------------------------------------------
    def do_stop(self,s):
        """stop one or more instances"""
        #TODO: complete_stop

        a=s.split()
        if len(a) == 0:
            P('    usage: stop instancelist...')
            return

        stopped_states=['stopping','stopped','terminated']
        # b is list of instances match that match wc
        b=[]
        for wc in a:
            if wc.find('*')==-1 and wc.find('?')==-1:
                b.append(wc)
            else:
                for c in [i[0] for i in self._instancelist() \
                                 if i[1] not in stopped_states]:
                    if fnmatch.fnmatch(c,wc):
                        b.append(c)

        if len(b) == 0:
            P('    error: no unstopped instance matches: %s'%s)
            return

        try:
            rv=self.conn.stop_instances(instance_ids=b)
            for i in rv:
                P('    stopping: %s'%(i))
        except boto.exception.EC2ResponseError,e:
            P('    error: %s'%(e.message))

    # IP >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

    # rough edits below >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

    #-----------------------------------------------------------------------
    def do_launch(self,s):
        """launch an instance"""
        x=self.conn.run_instances('ami-d7450be7',
                                key_name='mhtest',
                                instance_type='t2.micro',
                                security_groups=['mhsecurity'])
        print x

        # make sure we can ssh into it.  this probably can be
        # wrapped up into its own function and called once per
        # session.  perhaps make a command so that if we move
        # laptop between networks we can rejigger

        G='singlessh'

        #------------------------------------------------
        # create security group G if it does not exist
        exists=False
        for g in self.conn.get_all_security_groups():
            if g.name == G:
                exists=True
                break

        if exists == False:
            P('creating security group: %s'%(G))
            groups[G]=self.conn.create_security_group(G,'single location ssh')
        else:
            P('modifying security group: %s'%(G))

        #------------------------------------------------
        # delete any ingress rules from G.
        for r in g.rules:
            for cidr in r.grants:
                P('revoking grant: %s'%(cidr))
                g.revoke(r.ip_protocol,r.from_port,r.to_port,cidr_ip=cidr)

        #------------------------------------------------
        # and add our IP address as the sole ingress host
        mycidr=self.myip()+'/32'
        P('mycidr:%s:'%mycidr)
        P('authorizing: %s'%(mycidr))
        g.authorize(ip_protocol='tcp', from_port=22, to_port=22, cidr_ip=mycidr)


    # brignt ideas >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

    #-----------------------------------------------------------------------
    def do_hints(self,s):
        """print some useful hints"""
        P('COMING')

    #-----------------------------------------------------------------------
    def do_web(self,s):
        """open a web page with docs? status?"""
        P('COMING')

    #-----------------------------------------------------------------------
    def do_watcher(self,s):
        """run the watcher in another window"""
        P('COMING')

    #-----------------------------------------------------------------------
    def do_login(self,s):
        """modify the box to allow single ip login from this box"""
        P('COMING')

    #-----------------------------------------------------------------------
    def do_nologin(self,s):
        """modify the box to allow single login"""
        P('COMING')

    #-----------------------------------------------------------------------
    def do_region(self,s):
        """set the region"""
        P('COMING')

    #-----------------------------------------------------------------------
    def do_account(self,s):
        """set an account"""
        P('COMING')

    #-----------------------------------------------------------------------
    def do_account(self,s):
        """show accounts"""
        P('COMING')

    #-----------------------------------------------------------------------
    def do_reboot(self,s):
        """reboot an instance"""
        P('COMING')

    #-----------------------------------------------------------------------
    def do_console(self,s):
        """open an AWS web console"""
        P('COMING')

    # revisit these >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

    #-----------------------------------------------------------------------
    def THINK_ABOUT_THIS_do_terminate(self,s):
        """terminate an instance"""

        P("    use stop to stop an instance. don't terminate here for now...")
        return

        # BUG: nuke i0, should be for instance in instances???
        a=s.split()
        if len(a) == 0:
            P('  usage: terminate --all | id-list')
        elif len(a) == 1 and a[0] == '--all':
            reservations=self.conn.get_all_reservations()
            idlist=[]
            for r in reservations:
                instances=r.instances
                i0=instances[0]

                FORCE_TERMINATE=False
                if FORCE_TERMINATE:
                    # even if it's already termed, term it again!
                    idlist.append(i0.id)
                else:
                    if i0.state != 'terminated':
                        idlist.append(i0.id)
            if len(idlist) == 0:
                P('  no reservations to terminate')
            else:
                rr=self.conn.terminate_instances(instance_ids=idlist)
                P('  '+str(rr))
        else:
            try:
                rr=self.conn.terminate_instances(instance_ids=a)
                P('  '+str(rr))
            except boto.exception.EC2ResponseError,e:
                P('  '+e.message)

#-----------------------------------------------------------------------
def main():
    """The MAIN thing that you have to remember on this journey is,
       just be nice to everyone and always smile.
         -- Ed Sheeran
    """
    P0(AwshCmd.__doc__)
    cc=AwshCmd()

    # configuration files and
    # command history, with some goofiness to make it work on mac

    EBDIR=os.environ['HOME']+'/.ebaws'
    try:
        os.mkdir(EBDIR)
    except OSError,e:
        if e.args[0] != 17: # "File Exists")
            raise e

    #TODO: make this per-account
    historyFile=EBDIR+"/ebaws-history"
    open(historyFile,'a').close()

    if os.path.exists(historyFile):
        # gnu/libedit readline weirdness on macos. see
        # https://docs.python.org/2/library/readline.html
        if readline.__doc__.rfind('libedit') == -1:
            readline.read_history_file(historyFile)

    def writeHistory(historyFile=historyFile):
        readline.write_history_file(historyFile)
    atexit.register(writeHistory)

    while True:
        try:
            cc.cmdloop()
            break
        except KeyboardInterrupt:
            P('^C')
        except Exception,e:
            P('')
            P('*'*72)
            P('Unexpected Error:')
            traceback.print_exc()
            P('')
            P('please file a bug report')
            P('and include the above error details:')
            P('    https://github.com/marhar/aws/issues/new')
            P('*'*72)

if __name__=='__main__':
    main()
