#!/usr/local/sqlminus/bin/python
"""
instance-watcher -- watch aws instances

    https://github.com/marhar/aws       :  share and enjoy!
    Mark Harrison, marhar@gmail.com     :
"""

#TODO: shows stats for other things besides ec2
#TODO: clean up code structure since now it's a pure ansi terminal thing

import os,sys,time
import boto.ec2
import awshelpers
from pprint import pprint
from awshelpers import P,P0,tprint,tprintx

#-----------------------------------------------------------------------
_ho='\033[H'; _ed='\033[J'; _el='\033[K'  # ansi esc sequences
def doit(conn,profile):
    """show status with nice looking update"""

    P0('AWS (%s) %s %s                           build<3>\n'%\
                                           (profile,time.ctime(),_el))
    reservations=conn.get_all_reservations()
    # name | id | type | zone | state | status-checks | alarm-status

    dat=[]
    headers='id addr type zone state status alarm'.split()
    for r in reservations:
        instances=r.instances
        i0=instances[0]
        if i0.state != 'terminated':
            x=[i0.id,i0.ip_address,i0.instance_type,i0.placement,i0.state,'___','___']
            dat.append(x)
    tprintx(headers,dat)
    P0(_ed)

def doodle(period):
    """sleep while drawing the canonical timing doodle"""
    targ=time.time()+period
    n=2.0/8.0*2
    while time.time() < targ:
        P0('\r|  '+_ed); time.sleep(n)
        P0('\r/  '+_ed); time.sleep(n)
        P0('\r-  '+_ed); time.sleep(n)
        P0('\r\\  '+_ed); time.sleep(n)
        P0('\r|  '+_ed); time.sleep(n)
        P0('\r/  '+_ed); time.sleep(n)
        P0('\r-  '+_ed); time.sleep(n)
        P0('\r\\  '+_ed); time.sleep(n)

def main():
    if len(sys.argv) >= 2:
        profile=sys.argv[1]
    else:
        profile='default'

    cfg = awshelpers.readconfig('config')
    credentials=awshelpers.readconfig('credentials')

    if profile != '--all':
        p2=profile
        if profile != 'default':
            p2 = 'profile '+p2

        region = cfg[p2]['region']
        output = cfg[p2]['output']
        accesskey = credentials[profile]['aws_access_key_id']
        secretkey = credentials[profile]['aws_secret_access_key']

    allprofiles=[]
    for pp in credentials.keys():
        if pp != 'default':
            allprofiles.append(pp)
            
    if profile == '--all':
        while True:
            P0(_ho)
            for pp in allprofiles:
                pp2='profile '+pp
                conn = boto.ec2.connect_to_region(cfg[pp2]['region'],
                    aws_access_key_id=
                                 credentials[pp]['aws_access_key_id'],
                aws_secret_access_key=
                                 credentials[pp]['aws_secret_access_key'])
                doit(conn,pp)
                P(_el)
            doodle(3)
    else:
        conn = boto.ec2.connect_to_region(region,
                  aws_access_key_id=accesskey,
                  aws_secret_access_key=secretkey)
        while True:
            P0(_ho)
            doit(conn,profile)
            doodle(3)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        P('^C')
        P(_ed)
        sys.exit(0)
