# first make install, so that the revision number is bumped.
# then commit, so that that revision number is tied to the source.

foo:
	@echo try: make vbump

vbump:
	./patch_version awsh
	./patch_version instance-watcher
